In [1]:
import numpy as np

In [2]:
one_dimensional_arr = np.array([1,2,34,4,565,6778])

In [3]:
print(one_dimensional_arr)

[   1    2   34    4  565 6778]


In [4]:
two_dimensional_arr = np.array([ [1,2] , [3,4] , [5,6] ])

In [5]:
print(two_dimensional_arr)

[[1 2]
 [3 4]
 [5 6]]


In [10]:
random_arr = np.random.randint(low = 1, high= 100, size=(6,2))

In [11]:
print(random_arr)

[[60 25]
 [29 51]
 [91 29]
 [67 24]
 [29 50]
 [61 70]]


In [12]:
print(random_arr * 3)

[[180  75]
 [ 87 153]
 [273  87]
 [201  72]
 [ 87 150]
 [183 210]]


In [13]:
# Task 1:
# Your goal is to create a simple dataset consisting of a single feature and a label as follows:

# 1.Assign a sequence of integers from 6 to 20 (inclusive) to a NumPy array named feature.
# 2.Assign 15 values to a NumPy array named label such that:
#    label = (3)(feature) + 4

In [16]:
feature = np.arange(6,21)

In [17]:
print(feature)

[ 6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


In [18]:
label = feature

In [19]:
label = label * 3

In [20]:
label += 4

In [21]:
print(label)

[22 25 28 31 34 37 40 43 46 49 52 55 58 61 64]


In [30]:
# Task 2: Add Some Noise to the Dataset
# To make your dataset a little more realistic, insert a little random noise into each element of the label array you already created. To be more precise, modify each value assigned to label by adding a different random floating-point value between -2 and +2.

# Don't rely on broadcasting. Instead, create a noise array having the same dimension as label.

noise = np.random.random([15]) * 4


In [31]:
print(noise)

[2.54458002 0.92816182 3.19056843 0.30664487 3.37465736 1.55564067
 0.62343324 2.53887592 1.9810282  1.55439356 3.57518721 0.59967094
 1.68669243 2.05675776 2.22798717]


In [32]:
noise = noise -2

In [33]:
print(noise)

[ 0.54458002 -1.07183818  1.19056843 -1.69335513  1.37465736 -0.44435933
 -1.37656676  0.53887592 -0.0189718  -0.44560644  1.57518721 -1.40032906
 -0.31330757  0.05675776  0.22798717]
